version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./apps/backend/.env  # This loads ALL variables from backend/.env
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      mongodb:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    volumes:
      - ./apps/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://backend:8000
    ports:
      - "3000:3000"
    env_file:
      - ./apps/frontend/.env
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_started
        required: true

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --appendonly
      - "yes"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db

volumes:
  redis_data:
  mongodb_data: