import type { Metadata } from 'next';
import { getServerSession } from 'next-auth/next';
import 'antd/dist/reset.css';
import './globals.css';
import Providers from '@/lib/Providers';
import SessionProvider from './components/SessionProvider';
import AntRegistryProvider from '@/lib/AntRegistryProvider';
import { PropsWithChildren } from 'react';
import { ProgressbarProvider } from '@/lib/ProgressBarProvider';

export const metadata: Metadata = {
  title: 'Home | Style Vibe',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const session = await getServerSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ProgressbarProvider />
        <Providers>
          <SessionProvider session={session}>
            <AntRegistryProvider>{children}</AntRegistryProvider>
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
