# Use the official Node.js image as the base image
FROM node

# Create and set the working directory
WORKDIR /

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies with the legacy-peer-deps flag
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Compile TypeScript code
RUN npm run build

# Expose the port the app runs on
EXPOSE 8000

# Entry point
RUN ["chmod", "+x", "./entrypoint.sh"]

ENTRYPOINT [ "sh", "./entrypoint.sh" ]

# Command to run the application
CMD [ "npm", "start" ]
